name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

# Fake env variables to bypass env check during CI
env:
  NEXT_PUBLIC_APP_URL: "https://fake.com"
  NEXT_PUBLIC_TMDB_TOKEN: "fake-token"
  NEXT_PUBLIC_SITE_NAME: "fake-name"
  NEXT_PUBLIC_IMAGE_DOMAIN: "fake-domain"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prettier format check
        run: npm run format:check

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test
